version: '3.9'

services:
  nginx:
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - server-john
      - server-paul
      - server-george
      - server-ringo
    ports:
     - "3000:80"
    networks:
      local:
        ipv4_address: 173.18.0.2

  server-john:
    build: ./server
    links:
      - redis_1
      - redis_2
      - redis_3
    expose:
      - "3000"
    environment:
      - NAME=John
    networks:
      local:
        ipv4_address: 173.18.0.3

  server-paul:
    build: ./server
    links:
      - redis_1
      - redis_2
      - redis_3
    expose:
      - "3000"
    environment:
      - NAME=Paul
      - DEBUG=socket.io-redis-streams-adapter
    networks:
      local:
        ipv4_address: 173.18.0.4

  server-george:
    build: ./server
    links: 
      - redis_1
      - redis_2
      - redis_3
    expose:
      - "3000"
    environment:
      - NAME=George
    networks:
      local:
        ipv4_address: 173.18.0.5

  server-ringo:
    build: ./server
    links:
      - redis_1
      - redis_2
      - redis_3
    expose:
      - "3000"
    environment:
      - NAME=Ringo
    networks:
      local:
        ipv4_address: 173.18.0.6

  client:
    build: ./client
    links:
      - nginx
    networks:
      default:
      local:
        ipv4_address: 173.18.0.7
  
  # Here we have six Redis containers with Cluster mode enabled,
  # three of them will work as master nodes and each one of
  # will have a replica, so in case of failures, the replica becomes the master.
  # They are configured by the `cluster_initiator` container.
  redis_1:
    image: 'redis:6-alpine'
    container_name: redis_1
    ports:
      - "6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      local:
        ipv4_address: 173.18.0.8

  redis_2:
    image: 'redis:6-alpine'
    container_name: redis_2
    ports:
      - "6379"
    volumes:
      - redis_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      local:
        ipv4_address: 173.18.0.9

  redis_3:
    image: 'redis:6-alpine'
    container_name: redis_3
    ports:
      - "6379"
    volumes:
      - redis_3_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      local:
        ipv4_address: 173.18.0.10

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/16
          gateway: 173.18.0.1
  
volumes:
  redis_1_data: {}
  redis_2_data: {}
  redis_3_data: {}
  redis_4_data: {}
  redis_5_data: {}
  redis_6_data: {}
    